apps/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("registration/", views.RegisterFormView.as_view(), name="registration"),
    path("details/<int:pk>", views.UserDetailView.as_view(), name="details"),
    path("update/<int:pk>", views.UserUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", views.UserDeleteView.as_view(), name="delete"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("users/", include("apps.users.urls")),
    path("", include("apps.users.urls_root")),
]

apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    avatar = models.ImageField(
        max_length=255,
        upload_to="contacts/users/avatar/",
        blank=True,
        null=True,
    )

apps/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name", "password1", "password2", "avatar"]

apps/users/views.py
from django.contrib.auth import get_user_model, login
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import FormView, DetailView, UpdateView, DeleteView

from apps.users.forms import UserRegisterForm

User = get_user_model()


def index(request: WSGIRequest):
    return render(
        request=request,
        template_name="index.html",
    )


def about_us(request: WSGIRequest):
    return render(
        request=request,
        template_name="about_us.html",
    )


class RegisterFormView(FormView):
    form_class = UserRegisterForm
    template_name = "registration/register.html"
    success_url = reverse_lazy("root:index")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect("root:index")


class UserDetailView(DetailView):
    model = User
    template_name = "users/details.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Details User"
        return context


class UserUpdateView(UpdateView):
    model = User
    template_name = "users/update.html"
    fields = ("username", "email", "first_name", "last_name", "avatar")
    success_url = reverse_lazy("root:index")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Update Details User"
        return context


class UserDeleteView(DeleteView):
    model = User

    success_url = reverse_lazy("root:index")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Delete Account"
        return context

apps/templates/_helpers/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% if title %}
            {{ title }} |
        {% endif %}
        Django Apps
    </title>

    {# [connect_bootstrap] - [BEGIN] #}
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
            crossorigin="anonymous"
    >
    <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"
    ></script>
    {# [connect_bootstrap] - [END] #}
    <link
            href="{% static 'styles/index.css' %}"
            rel="stylesheet"
    >
    <link rel="icon" type="image/svg+xml" href="{% static "./favicons/favicon.svg" %}">
    <style>
        .footer {
            position: fixed;
            left: 50px;
            bottom: 2px;
            right: 10px;
            width: 95%;
            background-color: #c7c6c6;
            color: #020202;
            text-align: center;
            border-radius: 5px;
            margin: .5em;
        }
    </style>
</head>
<body>
<div class="container-fluid">
    {% include "_helpers/_header.html" %}
    {% block content %}
        Hello!
    {% endblock %}
</div>
<div class="footer">
    <p>
        Learn for your dreams! <a href=https://odessa.ithillel.ua/"> Computer school Hillel </a>
    </p>
    <p>
        Our Github <a href=https://github.com/Hillel-i-Python-Pro-i-2022-12-27"> Hillel Python Pro 27.12.2022 </a>
    </p>
</div>
</body>
</html>

apps/templates/_helpers/_header.html
<header>
    <nav class="navbar navbar-light navbar" style="background-color: rgba(200,200,201,0.87);
            border-radius: 5px;">
        <ul class="navbar-nav my-element-box">
            <div id="logo">
                <object
                    type="image/svg+xml"
                    data="/static/logo/logo.svg">
                    <img
                        src="/static/logo/logo.svg"
                        id="logo"
                        alt="">
                </object>
            </div>
            <div class="col my-element-box">
                <li class="nav-item">
                    <a class="nav-link" style="margin-inline: 15px;" href="{% url "root:index" %}">Main page</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="margin-inline: 15px;" href="{% url "admin:index" %}">Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="margin-inline: 15px;" href="{% url "root:about_us" %}">About us</a>
                </li>
            </div>
        </ul>
        <ul class="navbar-nav my-element-box">
            <div class="user-box">
            {% if user.is_authenticated %}
            <div class="user-info">
                <p>Hello! Dear, {{ user.username }}!</p>
                </div>
                    <a type="button" class="btn btn-warning" href="{% url "logout" %}">Log Out</a>
                    <a type="button" class="btn btn-info" href="{% url "users:details" pk=user.id %}">Details</a>
            {% else %}
                <p>You are unknown user!</p>
                <p>You need sign in or registration!!</p>
                <a type="button" class="btn btn-primary" href="{% url "login" %}">Log In</a>
                <a type="button" class="btn btn-primary" href="{% url "users:registration" %}">Registration</a>
            {% endif %}
            </div>
        </ul>
    </nav>
</header>

apps/templates/about_us.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h3>
        About us
    </h3>
    <div>
        This is the reference (basic project). To build on this project, you can easily start doing other projects.
    </div>
{% endblock %}

apps/templates/index.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <div>
        Main page (index)
    </div>
{% endblock %}

apps/templates/users/details.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <div class="col my-element-style">
        <div class="my-avatar">
            {% if user.avatar %}
                <img src="{{ user.avatar.url }}" alt="Avatar">
            {% endif %}
        </div>
    </div>
        <p>User name: {{ object.username }}</p>
        <p>First name: {{ object.first_name }}</p>
        <p>Last name: {{ object.last_name }}</p>
        <p>Email: {{ object.email }}</p>
        <p>Last login: {{ object.last_login }}</p>
        <p>Date registration: {{ object.date_joined }}</p>
    <a type="button" class="btn btn-primary" href="{% url "users:update" pk=object.id %}">Edit</a>
    <a type="button" class="btn btn-warning" href="{% url "users:delete" pk=object.id %}">Delete my account</a>
{% endblock %}

apps/templates/users/update.html
{% extends "_helpers/_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form | crispy }}

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

apps/templates/users/user_confirm_delete.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        <p>Are you sure you want to delete "{{ object }}"?</p>

        <button type="submit" class="btn btn-danger">Confirm</button>
    </form>
{% endblock %}